function:
  handler: src/uber-freight/create-shipment/index.handler
  name: uber-freight-create-shipment-${self:provider.stage}
  description: process and filters shipment apar table stream for 204 create shipment - ${self:provider.stage}
  runtime: nodejs18.x
  timeout: 30
  layers:
    - !Ref NodeModulesLambdaLayer

  events:
    - http:
        path: shipment/create
        method: post
        private: true

  package:
    patterns:
      - '!**/*'
      - 'src/uber-freight/create-shipment/**'

  environment:
    STAGE: ${self:provider.stage}
